install.packages("rtweet", dependencies = TRUE)
install.packages("sf")
install.packages("RSocrata")
install.packages("ggplot2")
install.packages("remotes")
remotes::install_github("anthonynorth/snapbox")
