install.packages("rtweet", dependencies = TRUE)
install.packages("sf")
install.packages("terra", repos = "https://rspatial.r-universe.dev")
install.packages("RSocrata")
install.packages("ggplot2")
install.packages("ggspatial")
install.packages("mapboxapi")
